apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: image-gitops
spec:
  components:
  - name: image-gitops
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/lgj101/GitOps-Demo
      pullInterval: 1m
      git:
        branch: image
      path: ./application
      imageRepository:
        image: harbor.dev.wh.digitalchina.com/kubevela/trigger-demo:v1.0
        secretRef: harbor-registry
        filterTags:
          pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
          extract: '$ts'
        policy:
          numerical:
            order: asc
        commitMessage: "Image: {{range .Updated.Images}}{{println .}}{{end}}"
